name: Build and Release

on:
    push:
        tags:
            - "v*"
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Run tests
              run: go test -v ./...

            - name: Check formatting
              run: |
                  if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
                    gofmt -s -l .
                    exit 1
                  fi

    build:
        needs: test
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Get version from tag
              id: version
              run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            - name: Build for multiple platforms
              run: |
                  mkdir -p dist

                  # Build for Windows
                  GOOS=windows GOARCH=amd64 go build -ldflags="-X 'github.com/MdShimulMahmud/go-arch-cli/cmd.Version=${{ steps.version.outputs.VERSION }}'" -o dist/go-arch-cli-windows-amd64.exe

                  # Build for Linux
                  GOOS=linux GOARCH=amd64 go build -ldflags="-X 'github.com/MdShimulMahmud/go-arch-cli/cmd.Version=${{ steps.version.outputs.VERSION }}'" -o dist/go-arch-cli-linux-amd64

                  # Build for macOS Intel
                  GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'github.com/MdShimulMahmud/go-arch-cli/cmd.Version=${{ steps.version.outputs.VERSION }}'" -o dist/go-arch-cli-darwin-amd64

                  # Build for macOS Apple Silicon
                  GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'github.com/MdShimulMahmud/go-arch-cli/cmd.Version=${{ steps.version.outputs.VERSION }}'" -o dist/go-arch-cli-darwin-arm64

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dist/go-arch-cli-windows-amd64.exe
                      dist/go-arch-cli-linux-amd64
                      dist/go-arch-cli-darwin-amd64
                      dist/go-arch-cli-darwin-arm64
                  generate_release_notes: true
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
